---
title: "network"
author: "Jiawei Huang"
date: "01/06/2021"
output: html_document
---

```{r}
ef = read.csv("../data/efeature_filtered.csv",header = T,stringsAsFactors = F)
gf = read.csv("../data/expMat.csv",header = T)
diff_ef = read.csv("../data/diff_ef.csv",header = T,stringsAsFactors = F)
diff_genes = read.csv("../data/diff_genes.csv",header = T,stringsAsFactors = F)
clustering = read.csv("../data/efeatures_NMA.csv",header = T,stringsAsFactors = F)
match = read.csv('../data/20200711_patchseq_metadata_mouse.csv',header=T,check.names = F,stringsAsFactors = F)
cellnames = c("gene",sapply(clustering$cellnames, gsub, pattern = "-", replacement = ".", fixed = TRUE))
gf = gf[!duplicated(gf$gene),cellnames]
rownames(ef) = ef[,1];ef = ef[,-1]
rownames(gf) = gf[,1];gf = gf[,-1]
cellnames = rownames(ef)
match$genotype = sapply(match$t_type,function(x){na.omit(unlist(strsplit(x, " ")))[1]})
t_type = sapply(cellnames,FUN = function(x){match$genotype[match$transcriptomics_sample_id==x]})
n = nrow(ef)
```

```{r}
cl1_genes = diff_genes$gene[diff_genes$cluster == "Cluster 1"]
net_gf = gf[c("Irf5","Spi1","Atf3"),]
head(net_gf)
net_gf = data.frame(t(log10(net_gf+1)))
#cor(net_gf[net_gf$Irf5>0 & net_gf$Spi1>0 & net_gf$Atf3>0,])
cor(net_gf)
```

```{r}
library(ggplot2)
library(gridExtra)
library(ggpubr)
p1 = ggplot(net_gf[diff_genes$cluster == "Cluster 1",],aes(x=Irf5,y=Atf3)) + geom_point(col = "#0C2D48",alpha = 0.6,size = 2) + theme_minimal() + stat_cor(method="pearson") + ggtitle("cluster1 visual")
p2 = ggplot(net_gf[diff_genes$cluster == "Cluster 1",],aes(x=Spi1,y=Atf3)) + geom_point(col = "#0C2D48",alpha = 0.6,size = 2) + theme_minimal() + stat_cor(method="pearson")+ ggtitle("cluster1 visual")
p3 = ggplot(net_gf,aes(x=Irf5,y=Atf3)) + geom_point(col = "#0C2D48",alpha = 0.6,size = 2) + theme_minimal() + stat_cor(method="pearson")+ ggtitle("all cells visual")
p4 = ggplot(net_gf,aes(x=Spi1,y=Atf3)) + geom_point(col = "#0C2D48",alpha = 0.6,size = 2) + theme_minimal() + stat_cor(method="pearson")+ ggtitle("all cells visual")
p = grid.arrange(p1, p2,p3,p4, nrow = 2,ncol = 2)
ggsave(file=paste0("../figure/network_Atf3.pdf"), p,width = 20,height = 20, units = "cm")
```



